# Site settings
baseURL = "https://savcisens.com/"
languageCode = "en-us"
title = "Germans Savcisens - Academic Portfolio"
publishDir = "public"
# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages) characters
hasCJKLanguage = false
enableRobotsTXT = true

dissabeRSS = true
disableKinds = ['RSS', 'taxonomy', 'term']


[params]
	author = "Germans Savcisens"
	description = "I am a Computational Social Scientist at Northeastern University. My research focuses on Algorithmic Fairness and Human Behaviour & Social Interaction."
	keywords = "life2vec, germans, savcisens, савчишен, scholar, life2vec, academic, northeastern"
	bio = "PhD, Computational Social Science"
	twitter = "germansave"

	enableRSS = false
	enableToc = true

	enableDisqus = false
	disqusShortname = "" #disqus shortname here

	enableSummary = false
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = false
	enablePlausible = true
	PlausibleID = "savcisens.com"

	enableTwitterCard = false
	# The url for twitter card image, default is avatar.png in static/images directory
	twitterCardImage = "images/avatar.jpg"

	# Add custom assets with their paths relative to the static folder
	customCSS = ['css/custom_v1.6.css']
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# show latest posts in single page
	showLatestPosts = false
	readMore = ""

	# Share
	enableShare = true
	tweet = ""
	share = ""

	# 404 page
	title404 = "Opps! This place is called 404."
	subtitle404 = "You entered in the wrong room buddy! Go back."

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "rounded"

	githubRepo = "https://github.com/carlomarxdk/portfolio"
	[params.social]
		bluesky = "https://bsky.app/profile/savcisens.com"
		github = "https://github.com/carlomarxdk"
		linkedin = "https://www.linkedin.com/in/germans-savcisens"
		envelope = "mailto:germans@savcisens.com"
		google-scholar = "https://scholar.google.com/citations?user=60I1M-oAAAAJ&hl=en"
		file = "/docs/Resume.pdf"


[menus]
  [[menus.main]]
    name = 'Publications'
    pageRef = '/publications'
    weight = 10
  [[menus.main]]
    name = 'Talks & Events'
    pageRef = '/talks'
    weight = 20
  [[menus.main]]
    name = 'Teaching & Services'
    pageRef = '/teaching'
    weight = 30
  [[menus.main]]
    name = 'Now'
    pageRef = '/now'
    weight = 40
  [[menus.main]]
    name = 'Contact'
    pageRef = '/contact'
    weight = 50

[taxonomies]
    category = "categories"
    tag = "tags"
  
[sitemap]
	changeFreq = ""  # Default change frequency (empty string)
	filename = "sitemap.xml"  # Sitemap file name
	priority = -1  # Default priority (-1 means omitted from rendered sitemap)


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true