# Site settings
baseURL = "https://savcisens.com/"
languageCode = "en"
title = "Scholar | Germans Savcisens"
publishDir = "public"
enableRobotsTXT = true

disableRSS = true
disableKinds = ['RSS', 'taxonomy', 'term']

[params]
	author = "Germans Savcisens"

	description = "I am a Computational Social Scientist at Northeastern University. My research focuses on stability of beliefs and knowledge in Large Language Models."
	keywords = ["life2vec", "germans savcisens", "savcisens","scholar","academic","northeastern","computational social science"]
	bio = "PhD, Computational Social Science"
	twitter = "germansave"
	
	enableToc = true
	enableDisqus = false
	disqusShortname = "" #disqus shortname here
	enableSummary = false
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = false
	enablePlausible = true
	PlausibleID = "savcisens.com"
	enableTwitterCard = true
	# The url for twitter card image, default is avatar.png in static/images directory
	twitterCardImage = "images/avatar.jpg"

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	olderPosts = ""
	newerPosts = ""
	copyright = "CC BY 4.0"

	# show latest posts in single page
	showLatestPosts = false
	readMore = ""

	# Share
	enableShare = false
	tweet = ""
	share = ""

	# 404 page
	title404 = "Opps! This place is called 404."
	subtitle404 = "You entered in the wrong room buddy! Go back."

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "rounded"

	githubRepo = "https://github.com/carlomarxdk/portfolio"

[params.structuredData]
	orcid = "https://orcid.org/0000-0002-5811-3230"
	googleScholar = "https://scholar.google.com/citations?user=60I1M-oAAAAJ&hl=en"
	jobTitle = "Postdoctoral Research Associate"
	scopusID = "58312119300"
	affiliation = "Northeastern University"

[params.social]
	bluesky = "https://bsky.app/profile/savcisens.com"
	github = "https://github.com/carlomarxdk"
	linkedin = "https://www.linkedin.com/in/germans-savcisens"
	envelope = "mailto:germans@savcisens.com"
	google-scholar = "https://scholar.google.com/citations?user=60I1M-oAAAAJ&hl=en"
	file = "/docs/Resume.pdf"

[menus]
  [[menus.main]]
    name = 'Publications'
    pageRef = '/publications'
    weight = 10
  [[menus.main]]
    name = 'Talks'
    pageRef = '/talks'
    weight = 20
  [[menus.main]]
    name = 'Teaching & Services'
    pageRef = '/teaching'
    weight = 30
  [[menus.main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 35
  [[menus.main]]
    name = 'Now'
    pageRef = '/now'
    weight = 40
  [[menus.main]]
    name = 'Contact'
    pageRef = '/contact'
    weight = 50

[taxonomies]
    category = "categories"
    tag = "tags"
  
[sitemap]
	changeFreq = "monthly"  # Default change frequency
	filename = "sitemap.xml"  # Sitemap file name
	priority = 0.5  # Default priority for pages


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      table = true
      strikethrough = true
      linkify = true
      taskList = true
      typographer = true
      definitionList = true
      footnote = true
	  fencedDiv = true

    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false